DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
    EXECUTE 'GRANT ALL ON SCHEMA auth TO postgres';
    EXECUTE 'GRANT ALL ON ALL TABLES IN SCHEMA auth TO postgres';
    EXECUTE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA auth TO postgres';
    EXECUTE 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA auth TO postgres';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO postgres';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO postgres';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'storage') THEN
    EXECUTE 'GRANT ALL ON SCHEMA storage TO postgres';
    EXECUTE 'GRANT ALL ON ALL TABLES IN SCHEMA storage TO postgres';
    EXECUTE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA storage TO postgres';
    EXECUTE 'GRANT ALL ON ALL FUNCTIONS IN SCHEMA storage TO postgres';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'realtime') THEN
    EXECUTE 'GRANT ALL ON SCHEMA realtime TO postgres';
  END IF;
END
$$;
