/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedOrgAdminRouteImport } from './routes/_authenticated/org-admin'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBoardsRouteImport } from './routes/_authenticated/boards'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedBoardsIndexRouteImport } from './routes/_authenticated/boards.index'
import { Route as AuthenticatedBoardsBoardIdRouteImport } from './routes/_authenticated/boards.$boardId'
import { Route as ApiPublicIcalTokenRouteImport } from './routes/api/public/ical.$token'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgAdminRoute = AuthenticatedOrgAdminRouteImport.update({
  id: '/org-admin',
  path: '/org-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBoardsRoute = AuthenticatedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBoardsIndexRoute =
  AuthenticatedBoardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBoardsRoute,
  } as any)
const AuthenticatedBoardsBoardIdRoute =
  AuthenticatedBoardsBoardIdRouteImport.update({
    id: '/$boardId',
    path: '/$boardId',
    getParentRoute: () => AuthenticatedBoardsRoute,
  } as any)
const ApiPublicIcalTokenRoute = ApiPublicIcalTokenRouteImport.update({
  id: '/api/public/ical/$token',
  path: '/api/public/ical/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/suspended': typeof SuspendedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/boards': typeof AuthenticatedBoardsRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/team': typeof AuthenticatedTeamRoute
  '/org-admin': typeof AuthenticatedOrgAdminRoute
  '/members': typeof AuthenticatedMembersRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/boards/': typeof AuthenticatedBoardsIndexRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/suspended': typeof SuspendedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/super-admin': typeof AuthenticatedSuperAdminRoute
  '/team': typeof AuthenticatedTeamRoute
  '/org-admin': typeof AuthenticatedOrgAdminRoute
  '/members': typeof AuthenticatedMembersRoute
  '/': typeof AuthenticatedIndexRoute
  '/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/boards': typeof AuthenticatedBoardsIndexRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/suspended': typeof SuspendedRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/boards': typeof AuthenticatedBoardsRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/org-admin': typeof AuthenticatedOrgAdminRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/boards/$boardId': typeof AuthenticatedBoardsBoardIdRoute
  '/_authenticated/boards/': typeof AuthenticatedBoardsIndexRoute
  '/api/public/ical/$token': typeof ApiPublicIcalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/suspended'
    | '/account'
    | '/settings'
    | '/boards'
    | '/calendar'
    | '/chat'
    | '/super-admin'
    | '/team'
    | '/org-admin'
    | '/members'
    | '/boards/$boardId'
    | '/boards/'
    | '/api/public/ical/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/suspended'
    | '/account'
    | '/settings'
    | '/calendar'
    | '/chat'
    | '/super-admin'
    | '/team'
    | '/org-admin'
    | '/members'
    | '/'
    | '/boards/$boardId'
    | '/boards'
    | '/api/public/ical/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/suspended'
    | '/_authenticated/account'
    | '/_authenticated/settings'
    | '/_authenticated/boards'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/super-admin'
    | '/_authenticated/team'
    | '/_authenticated/org-admin'
    | '/_authenticated/members'
    | '/_authenticated/'
    | '/_authenticated/boards/$boardId'
    | '/_authenticated/boards/'
    | '/api/public/ical/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SuspendedRoute: typeof SuspendedRoute
  ApiPublicIcalTokenRoute: typeof ApiPublicIcalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org-admin': {
      id: '/_authenticated/org-admin'
      path: '/org-admin'
      fullPath: '/org-admin'
      preLoaderRoute: typeof AuthenticatedOrgAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boards': {
      id: '/_authenticated/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AuthenticatedBoardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boards/': {
      id: '/_authenticated/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof AuthenticatedBoardsIndexRouteImport
      parentRoute: typeof AuthenticatedBoardsRoute
    }
    '/_authenticated/boards/$boardId': {
      id: '/_authenticated/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AuthenticatedBoardsBoardIdRouteImport
      parentRoute: typeof AuthenticatedBoardsRoute
    }
    '/api/public/ical/$token': {
      id: '/api/public/ical/$token'
      path: '/api/public/ical/$token'
      fullPath: '/api/public/ical/$token'
      preLoaderRoute: typeof ApiPublicIcalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBoardsRouteChildren {
  AuthenticatedBoardsBoardIdRoute: typeof AuthenticatedBoardsBoardIdRoute
  AuthenticatedBoardsIndexRoute: typeof AuthenticatedBoardsIndexRoute
}

const AuthenticatedBoardsRouteChildren: AuthenticatedBoardsRouteChildren = {
  AuthenticatedBoardsBoardIdRoute: AuthenticatedBoardsBoardIdRoute,
  AuthenticatedBoardsIndexRoute: AuthenticatedBoardsIndexRoute,
}

const AuthenticatedBoardsRouteWithChildren =
  AuthenticatedBoardsRoute._addFileChildren(AuthenticatedBoardsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBoardsRoute: typeof AuthenticatedBoardsRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedOrgAdminRoute: typeof AuthenticatedOrgAdminRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBoardsRoute: AuthenticatedBoardsRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedOrgAdminRoute: AuthenticatedOrgAdminRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SuspendedRoute: SuspendedRoute,
  ApiPublicIcalTokenRoute: ApiPublicIcalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
